db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=100shapes_shapes
  volumes:
    - /var/lib/postgresql/data
web:
  build: .
  environment:
    - SECRET='temp-key'
  ports:
    - "80:80"
  volumes:
    - /home/app/public
  links:
    - db